# Generated by Django 5.2.1 on 2025-05-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_no', models.CharField(max_length=30, unique=True)),
                ('file_content', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('section_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('registration_status', models.BooleanField(default=False)),
                ('ac_status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usermaster',
            },
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('reverted', 'Reverted'), ('completed', 'Completed')], default='in_transit', max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('file_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fileapp.file')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_logs', to='fileapp.usermaster')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_logs', to='fileapp.usermaster')),
            ],
            options={
                'db_table': 'filelog',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='fileapp.usermaster'),
        ),
    ]
