# Generated by Django 5.2.1 on 2025-05-28 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to='fileapp.usermaster'),
        ),
        migrations.AlterModelTable(
            name='file',
            table=None,
        ),
    ]
